name: darty_grits
description: A dart port of gritsgame
dependencies:
  browser: any
  args: any
  fukiya: 0.0.5
  box2d:
    git: https://github.com/darty-grits/dartbox2d.git
  game_loop: 0.7.0
  vector_math: 0.9.5
  simple_audio:
    git: https://github.com/johnmccutchan/simpleaudio.git