name: darty_grits
description: A sample web application
dependencies:
  browser: any
  args: any
  fukiya: 0.0.5
  box2d: 0.0.7
  game_loop: 0.7.0
  vector_math: 0.9.5
  simple_audio:
    git: https://github.com/johnmccutchan/simpleaudio.git