name: darty_grits
description: A dart port of gritsgame
dependencies:
  unittest: '>=0.4.1 <0.4.2'
  browser: '>=0.4.1 <0.4.2'
  bot: '>=0.15.0 <0.16.0'
  meta: '>=0.4.1 <0.4.2'
  html5lib: '>=0.4.0 <0.4.1'
  args: '>=0.4.1 <0.4.2'
  logging: '>=0.4.1 <0.4.2'
  pathos: '>=0.4.1 <0.4.2'
  source_maps: '>=0.4.0 <0.4.1'
  fukiya:
    git: https://github.com/Daegalus/fukiya.git
  box2d:
    git: https://github.com/darty-grits/dartbox2d.git
  game_loop: 0.7.0
  vector_math: 0.9.5
  simple_audio:
    git: https://github.com/johnmccutchan/simpleaudio.git